/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author MARY ANGEL
 */
public class AdminDashboard extends javax.swing.JFrame {
        private String employeeId; 

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(String empId) {
        initComponents();
        this.employeeId = empId; 
        loadEmployeeData();
        
    }
    private void loadEmployeeData() {
        try {
            Connection con = DBConnectionAdmin.getConnection();
            String sql = "SELECT full_name FROM employees WHERE employee_id = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, employeeId);  
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String fullName = rs.getString("full_name");
                adminName.setText(fullName);

            } else {
                adminName.setText("Employee not found.");
                JOptionPane.showMessageDialog(this, "No employee found with the ID: " + employeeId);
            }

            rs.close();
            ps.close();
            con.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }
    }
    
    private void logAdminAction(String action) {
        try {
            String folderName = "admin_logs";
            File folder = new File(folderName);
            if (!folder.exists()) {
                folder.mkdirs(); 
            }

            String date = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            File logFile = new File(folderName + "/" + date + ".txt");

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(logFile, true))) {
                String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                writer.write("[" + timestamp + "] Admin ID: " + employeeId + " - " + action);
                writer.newLine();
            }

        } catch (IOException e) {
            System.err.println("Error writing log: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        adminName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewAttendanceRecordsBTN = new javax.swing.JButton();
        viewLeaveRequestsBTN = new javax.swing.JButton();
        dashboardLogoutBTN4 = new javax.swing.JButton();
        viewEmployeesBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.gray)));
        jPanel1.setMaximumSize(new java.awt.Dimension(899, 599));
        jPanel1.setMinimumSize(new java.awt.Dimension(899, 599));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 95, 155));
        jPanel2.setMaximumSize(new java.awt.Dimension(900, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(900, 80));
        jPanel2.setLayout(null);

        adminName.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        adminName.setForeground(new java.awt.Color(255, 255, 255));
        adminName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(adminName);
        adminName.setBounds(560, 25, 260, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(830, 25, 32, 32);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whitelogo.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 10, 64, 64);

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Portal");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 30, 230, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 80);

        viewAttendanceRecordsBTN.setBackground(new java.awt.Color(0, 65, 106));
        viewAttendanceRecordsBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        viewAttendanceRecordsBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewAttendanceRecordsBTN.setText("View Attendance Records");
        viewAttendanceRecordsBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        viewAttendanceRecordsBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        viewAttendanceRecordsBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        viewAttendanceRecordsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttendanceRecordsBTNActionPerformed(evt);
            }
        });
        jPanel1.add(viewAttendanceRecordsBTN);
        viewAttendanceRecordsBTN.setBounds(300, 210, 290, 40);

        viewLeaveRequestsBTN.setBackground(new java.awt.Color(0, 65, 106));
        viewLeaveRequestsBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        viewLeaveRequestsBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewLeaveRequestsBTN.setText("View Leave Requests");
        viewLeaveRequestsBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        viewLeaveRequestsBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        viewLeaveRequestsBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        viewLeaveRequestsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLeaveRequestsBTNActionPerformed(evt);
            }
        });
        jPanel1.add(viewLeaveRequestsBTN);
        viewLeaveRequestsBTN.setBounds(300, 270, 290, 40);

        dashboardLogoutBTN4.setBackground(new java.awt.Color(0, 65, 106));
        dashboardLogoutBTN4.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        dashboardLogoutBTN4.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLogoutBTN4.setText("Logout");
        dashboardLogoutBTN4.setMaximumSize(new java.awt.Dimension(250, 40));
        dashboardLogoutBTN4.setMinimumSize(new java.awt.Dimension(250, 40));
        dashboardLogoutBTN4.setPreferredSize(new java.awt.Dimension(250, 40));
        dashboardLogoutBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardLogoutBTN4ActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardLogoutBTN4);
        dashboardLogoutBTN4.setBounds(340, 370, 200, 40);

        viewEmployeesBTN.setBackground(new java.awt.Color(0, 65, 106));
        viewEmployeesBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        viewEmployeesBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewEmployeesBTN.setText("View Employees");
        viewEmployeesBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        viewEmployeesBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        viewEmployeesBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        viewEmployeesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeesBTNActionPerformed(evt);
            }
        });
        jPanel1.add(viewEmployeesBTN);
        viewEmployeesBTN.setBounds(300, 150, 290, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 899, 599);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewAttendanceRecordsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttendanceRecordsBTNActionPerformed
        // TODO add your handling code here:
        AttendanceManagement attendanceManagement = new AttendanceManagement(employeeId);
        attendanceManagement.setVisible(true);
        logAdminAction("Viewed attendance records");
        this.dispose();
    }//GEN-LAST:event_viewAttendanceRecordsBTNActionPerformed

    private void viewLeaveRequestsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLeaveRequestsBTNActionPerformed
        // TODO add your handling code here:
        LeaveRecord leaveRecord = new LeaveRecord(employeeId);
        leaveRecord.setVisible(true);
        logAdminAction("Viewed leave requests");
        this.dispose();  
    }//GEN-LAST:event_viewLeaveRequestsBTNActionPerformed

    private void dashboardLogoutBTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardLogoutBTN4ActionPerformed
        // TODO add your handling code here:      
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            logAdminAction("Logged out");
            System.exit(0); 
        }
    }//GEN-LAST:event_dashboardLogoutBTN4ActionPerformed

    private void viewEmployeesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeesBTNActionPerformed
        // TODO add your handling code here:
        Employees employees = new Employees(employeeId);
        employees.setVisible(true);
        logAdminAction("Viewed employees");
        this.dispose();  
    }//GEN-LAST:event_viewEmployeesBTNActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminName;
    private javax.swing.JButton dashboardLogoutBTN4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton viewAttendanceRecordsBTN;
    private javax.swing.JButton viewEmployeesBTN;
    private javax.swing.JButton viewLeaveRequestsBTN;
    // End of variables declaration//GEN-END:variables
}
