/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author MARY ANGEL
 */
public class AdminLogin extends javax.swing.JFrame {
    private boolean passwordVisible = false;
    private String employeeId = "";

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }
    
    private void logAdminAction(String action) {
        try {
            String folderName = "admin_logs";
            File folder = new File(folderName);
            if (!folder.exists()) {
                folder.mkdirs(); 
            }

            String date = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            File logFile = new File(folderName + "/" + date + ".txt");

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(logFile, true))) {
                String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                writer.write("[" + timestamp + "] Admin ID: " + employeeId + " - " + action);
                writer.newLine();
            }

        } catch (IOException e) {
            System.err.println("Error writing log: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        adminLoginBTN = new javax.swing.JButton();
        adminIDTF = new javax.swing.JTextField();
        adminPassPF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adminSeePassBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 350));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray), null));
        jPanel2.setMaximumSize(new java.awt.Dimension(420, 350));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 350));
        jPanel2.setLayout(null);

        adminLoginBTN.setBackground(new java.awt.Color(0, 65, 106));
        adminLoginBTN.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        adminLoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        adminLoginBTN.setText("Login");
        adminLoginBTN.setMaximumSize(new java.awt.Dimension(230, 35));
        adminLoginBTN.setMinimumSize(new java.awt.Dimension(230, 35));
        adminLoginBTN.setPreferredSize(new java.awt.Dimension(230, 35));
        adminLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginBTNActionPerformed(evt);
            }
        });
        jPanel2.add(adminLoginBTN);
        adminLoginBTN.setBounds(100, 230, 230, 35);

        adminIDTF.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        adminIDTF.setMaximumSize(new java.awt.Dimension(230, 35));
        adminIDTF.setMinimumSize(new java.awt.Dimension(230, 35));
        adminIDTF.setPreferredSize(new java.awt.Dimension(230, 35));
        jPanel2.add(adminIDTF);
        adminIDTF.setBounds(160, 80, 230, 35);

        adminPassPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminPassPF.setMaximumSize(new java.awt.Dimension(230, 35));
        adminPassPF.setMinimumSize(new java.awt.Dimension(230, 35));
        adminPassPF.setPreferredSize(new java.awt.Dimension(230, 35));
        adminPassPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPassPFActionPerformed(evt);
            }
        });
        jPanel2.add(adminPassPF);
        adminPassPF.setBounds(160, 130, 200, 35);

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 45, 75));
        jLabel1.setText("M&J SYSTEMS CO.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 20, 230, 35);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel2.setText("Admin ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 90, 110, 16);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 140, 90, 16);

        adminSeePassBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        adminSeePassBTN.setMaximumSize(new java.awt.Dimension(30, 35));
        adminSeePassBTN.setMinimumSize(new java.awt.Dimension(30, 35));
        adminSeePassBTN.setPreferredSize(new java.awt.Dimension(30, 35));
        adminSeePassBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSeePassBTNActionPerformed(evt);
            }
        });
        jPanel2.add(adminSeePassBTN);
        adminSeePassBTN.setBounds(360, 130, 30, 35);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 10, 64, 64);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminPassPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPassPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPassPFActionPerformed

    private void adminLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginBTNActionPerformed
        // TODO add your handling code here:
        String adminId = adminIDTF.getText().trim();
        String adminPass = new String(adminPassPF.getPassword()).trim();

        if (adminId.isEmpty() || adminPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = DBConnectionAdmin.getConnection()) {
            String sql = "SELECT * FROM employees WHERE employee_id = ? AND department = 'HR' AND position = 'Officer' AND role = 'Admin'";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, adminId);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String dbPassword = rs.getString("password");
                String status = rs.getString("status");

                if (!"Active".equalsIgnoreCase(status)) {
                    JOptionPane.showMessageDialog(this, "Your account is inactive. Contact system administrator.", "Access Denied", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                if (adminPass.equals(dbPassword)) {
                    this.employeeId = rs.getString("employee_id");
                            
                    logAdminAction("Admin login successfully");
                    JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

                    String employeeId = rs.getString("employee_id");

                    AdminDashboard dashboard = new AdminDashboard(employeeId);
                    dashboard.setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Admin ID not found or does not meet admin criteria (MJAD###, HR, Officer).", "Login Failed", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_adminLoginBTNActionPerformed

    private void adminSeePassBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSeePassBTNActionPerformed
        // TODO add your handling code here:
        if (passwordVisible) {
            adminPassPF.setEchoChar('•'); 
            passwordVisible = false;
        } else {
            adminPassPF.setEchoChar((char) 0); 
            passwordVisible = true;    
    }
    }//GEN-LAST:event_adminSeePassBTNActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminIDTF;
    private javax.swing.JButton adminLoginBTN;
    private javax.swing.JPasswordField adminPassPF;
    private javax.swing.JButton adminSeePassBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
