/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Date;

/**
 *
 * @author MARY ANGEL
 */
public class LeaveRecord extends javax.swing.JFrame {
    private String employeeId;

    /**
     * Creates new form LeaveRecord
     */
    public LeaveRecord(String empId) {
        initComponents();
        this.employeeId = empId;
        setCurrentDate();     
        startClock();
    }
    
    private void setCurrentDate() {
        LocalDate today = LocalDate.now();
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        JLabelDate.setText(today.format(dateFormat));
    }
        private void startClock() {
            Timer timer = new Timer(1000, new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    LocalTime now = LocalTime.now();
                    DateTimeFormatter timeFormat = DateTimeFormatter.ofPattern("HH:mm:ss"); 
                    JLabelTime.setText(now.format(timeFormat));
                }
            });
            timer.start();
    }
        
    private void logAdminAction(String action) {
        try {
            String folderName = "admin_logs";
            File folder = new File(folderName);
            if (!folder.exists()) {
                folder.mkdirs(); 
            }

            String date = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            File logFile = new File(folderName + "/" + date + ".txt");

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(logFile, true))) {
                String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                writer.write("[" + timestamp + "] Admin ID: " + employeeId + " - " + action);
                writer.newLine();
            }

        } catch (IOException e) {
            System.err.println("Error writing log: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JLabelDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JLabelTime = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaveRecordTBL = new javax.swing.JTable();
        leaveApproveBTN = new javax.swing.JButton();
        statusJComboBox = new javax.swing.JComboBox<>();
        leaveRejectBTN = new javax.swing.JButton();
        ReturnDashboardBTN = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 95, 155));
        jPanel4.setMaximumSize(new java.awt.Dimension(900, 80));
        jPanel4.setMinimumSize(new java.awt.Dimension(900, 80));
        jPanel4.setLayout(null);

        JLabelDate.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        JLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        JLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel4.add(JLabelDate);
        JLabelDate.setBounds(710, 20, 150, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whitelogo.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 10, 64, 64);

        JLabelTime.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        JLabelTime.setForeground(new java.awt.Color(255, 255, 255));
        JLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel4.add(JLabelTime);
        JLabelTime.setBounds(610, 40, 250, 20);

        jLabel12.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Leave Record Portal");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(90, 30, 230, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 900, 80);

        leaveRecordTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Leave Type", "Start Date", "End Date", "Status", "Reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(leaveRecordTBL);
        if (leaveRecordTBL.getColumnModel().getColumnCount() > 0) {
            leaveRecordTBL.getColumnModel().getColumn(0).setResizable(false);
            leaveRecordTBL.getColumnModel().getColumn(1).setResizable(false);
            leaveRecordTBL.getColumnModel().getColumn(2).setResizable(false);
            leaveRecordTBL.getColumnModel().getColumn(3).setResizable(false);
            leaveRecordTBL.getColumnModel().getColumn(4).setResizable(false);
            leaveRecordTBL.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 160, 710, 320);

        leaveApproveBTN.setBackground(new java.awt.Color(56, 142, 60));
        leaveApproveBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        leaveApproveBTN.setForeground(new java.awt.Color(255, 255, 255));
        leaveApproveBTN.setText("Approve");
        leaveApproveBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        leaveApproveBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        leaveApproveBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        leaveApproveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveApproveBTNActionPerformed(evt);
            }
        });
        jPanel1.add(leaveApproveBTN);
        leaveApproveBTN.setBounds(500, 120, 150, 30);

        statusJComboBox.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        statusJComboBox.setForeground(new java.awt.Color(0, 65, 106));
        statusJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Pending", "Approved ", "Rejected" }));
        statusJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(statusJComboBox);
        statusJComboBox.setBounds(170, 130, 170, 22);

        leaveRejectBTN.setBackground(new java.awt.Color(211, 47, 47));
        leaveRejectBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        leaveRejectBTN.setForeground(new java.awt.Color(255, 255, 255));
        leaveRejectBTN.setText("Reject");
        leaveRejectBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        leaveRejectBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        leaveRejectBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        leaveRejectBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveRejectBTNActionPerformed(evt);
            }
        });
        jPanel1.add(leaveRejectBTN);
        leaveRejectBTN.setBounds(660, 120, 150, 30);

        ReturnDashboardBTN.setBackground(new java.awt.Color(0, 65, 106));
        ReturnDashboardBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        ReturnDashboardBTN.setForeground(new java.awt.Color(255, 255, 255));
        ReturnDashboardBTN.setText("Back to Dashboard");
        ReturnDashboardBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        ReturnDashboardBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        ReturnDashboardBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        ReturnDashboardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnDashboardBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ReturnDashboardBTN);
        ReturnDashboardBTN.setBounds(370, 500, 200, 40);

        jLabel11.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 65, 106));
        jLabel11.setText("Status:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 130, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void leaveApproveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveApproveBTNActionPerformed
        // TODO add your handling code here:
        int selectedRow = leaveRecordTBL.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to approve.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String status = leaveRecordTBL.getValueAt(selectedRow, 4).toString();
        if (!status.equalsIgnoreCase("Pending")) {
            JOptionPane.showMessageDialog(this, "Only Pending leave requests can be approved.", "Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Approve this leave request?", "Confirm Approval", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        String empId = leaveRecordTBL.getValueAt(selectedRow, 0).toString();
        Date startDate = (Date) leaveRecordTBL.getValueAt(selectedRow, 2);
        Date endDate = (Date) leaveRecordTBL.getValueAt(selectedRow, 3);

        try (Connection conn = DBConnectionAdmin.getConnection()) {
            String sql = "UPDATE leave_requests SET status = 'Approved' WHERE employee_id = ? AND start_date = ? AND end_date = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, empId);
            pst.setDate(2, new java.sql.Date(startDate.getTime()));
            pst.setDate(3, new java.sql.Date(endDate.getTime()));

            int updated = pst.executeUpdate();
            if (updated > 0) {
                logAdminAction("Approved leave request for Employee ID: " + empId + " from " + startDate + " to " + endDate);
                JOptionPane.showMessageDialog(this, "Leave request approved.", "Success", JOptionPane.INFORMATION_MESSAGE);
                statusJComboBoxActionPerformed(null); // Refresh table
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error approving leave.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_leaveApproveBTNActionPerformed

    private void leaveRejectBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveRejectBTNActionPerformed
        // TODO add your handling code here:
        int selectedRow = leaveRecordTBL.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to reject.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String status = leaveRecordTBL.getValueAt(selectedRow, 4).toString();
        if (!status.equalsIgnoreCase("Pending")) {
            JOptionPane.showMessageDialog(this, "Only Pending leave requests can be rejected.", "Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Reject this leave request?", "Confirm Rejection", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        String empId = leaveRecordTBL.getValueAt(selectedRow, 0).toString();
        Date startDate = (Date) leaveRecordTBL.getValueAt(selectedRow, 2);
        Date endDate = (Date) leaveRecordTBL.getValueAt(selectedRow, 3);

        try (Connection conn = DBConnectionAdmin.getConnection()) {
            String sql = "UPDATE leave_requests SET status = 'Rejected' WHERE employee_id = ? AND start_date = ? AND end_date = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, empId);
            pst.setDate(2, new java.sql.Date(startDate.getTime()));
            pst.setDate(3, new java.sql.Date(endDate.getTime()));

            int updated = pst.executeUpdate();
            if (updated > 0) {
                logAdminAction("Rejected leave request for Employee ID: " + empId + " from " + startDate + " to " + endDate);
                JOptionPane.showMessageDialog(this, "Leave request rejected.", "Success", JOptionPane.INFORMATION_MESSAGE);
                statusJComboBoxActionPerformed(null); // Refresh table
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error rejecting leave.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_leaveRejectBTNActionPerformed

    private void ReturnDashboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnDashboardBTNActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(employeeId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnDashboardBTNActionPerformed

    private void statusJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusJComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedStatus = statusJComboBox.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) leaveRecordTBL.getModel();
        model.setRowCount(0); // Clear table

        String sql = "SELECT employee_id, leave_type, start_date, end_date, status, reason FROM leave_requests";
        if (!selectedStatus.equalsIgnoreCase("All")) {
            sql += " WHERE LOWER(TRIM(status)) = LOWER(TRIM(?))";
        }

        try (Connection conn = DBConnectionAdmin.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            if (!selectedStatus.equalsIgnoreCase("All")) {
                pst.setString(1, selectedStatus);
            }

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("employee_id"),
                    rs.getString("leave_type"),
                    rs.getDate("start_date"),
                    rs.getDate("end_date"),
                    rs.getString("status"),
                    rs.getString("reason")
                });
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error filtering leave records.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_statusJComboBoxActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelDate;
    private javax.swing.JLabel JLabelTime;
    private javax.swing.JButton ReturnDashboardBTN;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leaveApproveBTN;
    private javax.swing.JTable leaveRecordTBL;
    private javax.swing.JButton leaveRejectBTN;
    private javax.swing.JComboBox<String> statusJComboBox;
    // End of variables declaration//GEN-END:variables
}
