/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ChangePIN extends javax.swing.JFrame {
    MainApp main;
    /**
     * Creates new form Deposit
     */
    public ChangePIN(MainApp m) {
        initComponents();
        setSize(1366, 768);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setLocationRelativeTo(null); // center
        
        this.main = m;
    }
    
   





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancelBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        confirmBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        confirmPINTF = new javax.swing.JPasswordField();
        oldPINTF = new javax.swing.JPasswordField();
        newPINTF = new javax.swing.JPasswordField();
        seePW = new javax.swing.JButton();
        seePW1 = new javax.swing.JButton();
        seePW2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE PIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(820, 200, 260, 40);

        cancelBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        cancelBTN.setText("Cancel");
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBTN);
        cancelBTN.setBounds(910, 490, 210, 40);

        backBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        backBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backIcon.png"))); // NOI18N
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN);
        backBTN.setBounds(1120, 650, 150, 60);

        confirmBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        confirmBTN.setText("Confirm");
        confirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBTNActionPerformed(evt);
            }
        });
        getContentPane().add(confirmBTN);
        confirmBTN.setBounds(660, 490, 210, 40);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Enter current PIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 360, 190, 40);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Enter new PIN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 360, 190, 40);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Confirm new PIN");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(650, 430, 190, 40);

        confirmPINTF.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        confirmPINTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(confirmPINTF);
        confirmPINTF.setBounds(860, 430, 250, 40);

        oldPINTF.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        oldPINTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(oldPINTF);
        oldPINTF.setBounds(340, 360, 250, 40);

        newPINTF.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        newPINTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(newPINTF);
        newPINTF.setBounds(860, 360, 250, 40);

        seePW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seePW.setForeground(new java.awt.Color(255, 255, 255));
        seePW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seePass.png"))); // NOI18N
        seePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePWActionPerformed(evt);
            }
        });
        getContentPane().add(seePW);
        seePW.setBounds(1110, 360, 40, 40);

        seePW1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seePW1.setForeground(new java.awt.Color(255, 255, 255));
        seePW1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seePass.png"))); // NOI18N
        seePW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePW1ActionPerformed(evt);
            }
        });
        getContentPane().add(seePW1);
        seePW1.setBounds(1110, 430, 40, 40);

        seePW2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seePW2.setForeground(new java.awt.Color(255, 255, 255));
        seePW2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seePass.png"))); // NOI18N
        seePW2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePW2ActionPerformed(evt);
            }
        });
        getContentPane().add(seePW2);
        seePW2.setBounds(590, 360, 40, 40);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/changePin.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-40, 0, 1410, 770);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        // TODO add your handling code here:  
       oldPINTF.setText("");
       newPINTF.setText("");
       confirmPINTF.setText("");
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        dispose();        
    }//GEN-LAST:event_backBTNActionPerformed
    private boolean isValidPIN(String pin) {    
    return pin.matches("\\d{4}");
}
    private void confirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBTNActionPerformed
        // TODO add your handling code here:
    String oldPIN = new String(oldPINTF.getPassword());
    String newPIN = new String(newPINTF.getPassword());
    String confirmPIN = new String(confirmPINTF.getPassword());
    
    if (!oldPIN.equals(main.getPin())) {
        JOptionPane.showMessageDialog(null, "Incorrect old PIN.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!isValidPIN(newPIN)) {
        JOptionPane.showMessageDialog(null, "Invalid new PIN. It should be a 4-digit number.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!newPIN.equals(confirmPIN)) {
        JOptionPane.showMessageDialog(null, "New PIN does not match the confirmed PIN.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    main.updatePIN(newPIN);
    JOptionPane.showMessageDialog(null, "PIN successfully updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
    dispose();
    }//GEN-LAST:event_confirmBTNActionPerformed

    
    
    private boolean passwordVisible = false;
    private void seePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePWActionPerformed
        // TODO add your handling code here:
         passwordVisible = !passwordVisible;

    if (passwordVisible) {
        oldPINTF.setEchoChar((char) 0);
        newPINTF.setEchoChar((char) 0);
        confirmPINTF.setEchoChar((char) 0);
    } else {
        oldPINTF.setEchoChar('*');
        newPINTF.setEchoChar('*');
        confirmPINTF.setEchoChar('*');
    }
    }//GEN-LAST:event_seePWActionPerformed

    private void seePW2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePW2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seePW2ActionPerformed

    private void seePW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePW1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seePW1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton cancelBTN;
    private javax.swing.JButton confirmBTN;
    private javax.swing.JPasswordField confirmPINTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField newPINTF;
    private javax.swing.JPasswordField oldPINTF;
    private javax.swing.JButton seePW;
    private javax.swing.JButton seePW1;
    private javax.swing.JButton seePW2;
    // End of variables declaration//GEN-END:variables
}
