/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import java.io.FileReader;
import classes.Accounts;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

   MainApp main;
   CreateAccount createAccount; 
   
    /**
     * Creates new form Login
     */
    public Login(MainApp main) {
        initComponents();
        setSize(1366, 768);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setLocationRelativeTo(null); // center

        
        this.main = main;   
    }

   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seePW = new javax.swing.JButton();
        pinTF = new javax.swing.JPasswordField();
        loginBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        accNOTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        caBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        seePW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seePW.setForeground(new java.awt.Color(255, 255, 255));
        seePW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seePass.png"))); // NOI18N
        seePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePWActionPerformed(evt);
            }
        });
        getContentPane().add(seePW);
        seePW.setBounds(1130, 430, 60, 70);

        pinTF.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        pinTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTFActionPerformed(evt);
            }
        });
        getContentPane().add(pinTF);
        pinTF.setBounds(800, 430, 390, 70);

        loginBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        loginBTN.setText("Login");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        getContentPane().add(loginBTN);
        loginBTN.setBounds(890, 530, 140, 40);

        exitBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(exitBTN);
        exitBTN.setBounds(1050, 530, 140, 40);

        accNOTF.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        accNOTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(accNOTF);
        accNOTF.setBounds(800, 350, 390, 60);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PIN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 440, 170, 50);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 350, 170, 50);

        caBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        caBTN.setText("Create Account");
        caBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caBTNActionPerformed(evt);
            }
        });
        getContentPane().add(caBTN);
        caBTN.setBounds(970, 590, 220, 40);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 768);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        String enteredAccountNumber = accNOTF.getText().trim();
    String enteredPIN = new String(pinTF.getPassword()).trim();

    if (enteredAccountNumber.length() != 6 || !enteredAccountNumber.matches("\\d{6}")) {
        JOptionPane.showMessageDialog(this, "Account number must be 6 digits.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    String[] accountInfo = Accounts.readAccountAndPIN(enteredAccountNumber);
    double amount = Accounts.readAmount(enteredAccountNumber);
    String currency = Accounts.readCurrency(enteredAccountNumber);

    if (accountInfo != null && accountInfo.length == 2) {
            String savedAccountNumber = accountInfo[0];
            String savedPIN = accountInfo[1];

            if (enteredAccountNumber.equals(savedAccountNumber) && enteredPIN.equals(savedPIN)) {
                JOptionPane.showMessageDialog(this, "Login Successful!");
                MainApp mainApp = new MainApp(createAccount, this, enteredAccountNumber, enteredPIN, amount, currency);
                mainApp.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Account Number or PIN. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Account not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        accNOTF.setText("");
        pinTF.setText("");
    }//GEN-LAST:event_loginBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
       JFrame frame = new JFrame("EXIT");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want Exit", "EXIT", 
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }       
    }//GEN-LAST:event_exitBTNActionPerformed

    private boolean passwordVisible = false;
    private void pinTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinTFActionPerformed

    private void seePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePWActionPerformed
        // TODO add your handling code here:
        passwordVisible = !passwordVisible;

        if (passwordVisible) {
            pinTF.setEchoChar((char) 0); 
        } else {
            pinTF.setEchoChar('*'); 
        }
    }//GEN-LAST:event_seePWActionPerformed

    private void caBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caBTNActionPerformed
        // TODO add your handling code here:
        if (createAccount == null) {
            createAccount = new CreateAccount(main, this);
        }
        
        createAccount.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_caBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNOTF;
    private javax.swing.JButton caBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBTN;
    private javax.swing.JPasswordField pinTF;
    private javax.swing.JButton seePW;
    // End of variables declaration//GEN-END:variables
}