/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Transfer extends javax.swing.JFrame {
    MainApp main;
    /**
     * Creates new form Deposit
     */
    public Transfer(MainApp m) {
        initComponents();
        setSize(1366, 768);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setLocationRelativeTo(null); // center
        
        this.main = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transferAmountTF = new javax.swing.JTextField();
        cancelBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        confirmBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        accNoTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        transferAmountTF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        transferAmountTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        transferAmountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAmountTFActionPerformed(evt);
            }
        });
        getContentPane().add(transferAmountTF);
        transferAmountTF.setBounds(870, 260, 400, 50);

        cancelBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        cancelBTN.setText("Cancel");
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBTN);
        cancelBTN.setBounds(1110, 360, 140, 40);

        backBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        backBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backIcon.png"))); // NOI18N
        backBTN.setText("Back");
        backBTN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN);
        backBTN.setBounds(1100, 630, 160, 60);

        confirmBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        confirmBTN.setText("Confirm");
        confirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBTNActionPerformed(evt);
            }
        });
        getContentPane().add(confirmBTN);
        confirmBTN.setBounds(900, 360, 140, 40);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 270, 130, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Account No.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(690, 160, 140, 40);

        accNoTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accNoTF.setForeground(new java.awt.Color(2, 12, 66));
        accNoTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        accNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoTFActionPerformed(evt);
            }
        });
        getContentPane().add(accNoTF);
        accNoTF.setBounds(870, 150, 400, 50);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transfer.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -20, 1380, 810);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transferAmountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAmountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmountTFActionPerformed

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        // TODO add your handling code here:
        transferAmountTF.setText("");
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        dispose();   
    }//GEN-LAST:event_backBTNActionPerformed

    private void confirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBTNActionPerformed
        String receiverAccountNumber = accNoTF.getText();

        double amount;
        try {
            amount = Double.parseDouble(transferAmountTF.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid transfer amount.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String receiverCurrency = main.getReceiverCurrency(receiverAccountNumber);
        main.transfer(amount, receiverAccountNumber, receiverCurrency);

        transferAmountTF.setText("");
        accNoTF.setText("");
    }//GEN-LAST:event_confirmBTNActionPerformed

    private void accNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNoTF;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton cancelBTN;
    private javax.swing.JButton confirmBTN;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField transferAmountTF;
    // End of variables declaration//GEN-END:variables
}
