/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

import javax.swing.JTable;

/**
 *
 * @author MARY ANGEL
 */
public class RF extends javax.swing.JFrame {

    /**
     * Creates new form RF
     */
    public RF() {
        initComponents();
    }
        // Add this method inside RF class
    public void populateRF(String studentID, String studentName, String course, String yearSection, 
                           String acadYear, String semester, String gwa, String dateTime) {
        // Populate the text fields with the student information
        rfStudIDTF.setText(studentID);
        rfStudNameTF.setText(studentName);
        rfCourseTF.setText(course);
        yearSectionTF.setText(yearSection);
        acadYearTF.setText(acadYear);
        semTF.setText(semester);
        rfGWATF.setText(gwa);
        dateTimeTF.setText(dateTime);
    }
    public JTable getGradeTable() {
    return rfgradeTable;

      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradeStudIDTF = new javax.swing.JTextField();
        gradeStudIDTF1 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        rfgradeTable = new javax.swing.JTable();
        jLabel56 = new javax.swing.JLabel();
        rfStudIDTF = new javax.swing.JTextField();
        rfStudNameTF = new javax.swing.JTextField();
        rfCourseTF = new javax.swing.JTextField();
        yearSectionTF = new javax.swing.JTextField();
        acadYearTF = new javax.swing.JTextField();
        semTF = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        rfGWATF = new javax.swing.JTextField();
        dateTimeTF = new javax.swing.JTextField();

        gradeStudIDTF.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        gradeStudIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeStudIDTFActionPerformed(evt);
            }
        });

        gradeStudIDTF1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        gradeStudIDTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeStudIDTF1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(669, 638));
        getContentPane().setLayout(null);

        jLabel58.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Student Registration Form");
        jLabel58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel58);
        jLabel58.setBounds(190, 40, 255, 22);

        jLabel50.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel50.setText("Student ID:");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(20, 120, 94, 34);

        jLabel51.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel51.setText("Name:");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(30, 170, 90, 29);

        jLabel52.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel52.setText("Course:");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(20, 210, 120, 29);

        jLabel53.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel53.setText("Year & Section:");
        getContentPane().add(jLabel53);
        jLabel53.setBounds(380, 120, 110, 29);

        jLabel54.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel54.setText("Academic Year:");
        getContentPane().add(jLabel54);
        jLabel54.setBounds(380, 160, 120, 29);

        jLabel55.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel55.setText("Semester:");
        getContentPane().add(jLabel55);
        jLabel55.setBounds(380, 200, 90, 28);

        rfgradeTable.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        rfgradeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ", "Grade", "Units"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rfgradeTable.setEnabled(false);
        rfgradeTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                rfgradeTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane6.setViewportView(rfgradeTable);
        if (rfgradeTable.getColumnModel().getColumnCount() > 0) {
            rfgradeTable.getColumnModel().getColumn(0).setResizable(false);
            rfgradeTable.getColumnModel().getColumn(1).setResizable(false);
            rfgradeTable.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(20, 300, 619, 140);

        jLabel56.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel56.setText("GWA:");
        getContentPane().add(jLabel56);
        jLabel56.setBounds(30, 490, 50, 28);

        rfStudIDTF.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        rfStudIDTF.setEnabled(false);
        rfStudIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfStudIDTFActionPerformed(evt);
            }
        });
        getContentPane().add(rfStudIDTF);
        rfStudIDTF.setBounds(120, 120, 244, 30);

        rfStudNameTF.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        rfStudNameTF.setEnabled(false);
        rfStudNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfStudNameTFActionPerformed(evt);
            }
        });
        getContentPane().add(rfStudNameTF);
        rfStudNameTF.setBounds(120, 170, 244, 30);

        rfCourseTF.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        rfCourseTF.setEnabled(false);
        rfCourseTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfCourseTFActionPerformed(evt);
            }
        });
        getContentPane().add(rfCourseTF);
        rfCourseTF.setBounds(120, 213, 244, 30);

        yearSectionTF.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        yearSectionTF.setEnabled(false);
        yearSectionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearSectionTFActionPerformed(evt);
            }
        });
        getContentPane().add(yearSectionTF);
        yearSectionTF.setBounds(500, 120, 141, 30);

        acadYearTF.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        acadYearTF.setEnabled(false);
        acadYearTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acadYearTFActionPerformed(evt);
            }
        });
        getContentPane().add(acadYearTF);
        acadYearTF.setBounds(500, 160, 141, 30);

        semTF.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        semTF.setEnabled(false);
        semTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semTFActionPerformed(evt);
            }
        });
        getContentPane().add(semTF);
        semTF.setBounds(500, 200, 141, 30);

        jLabel57.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel57.setText("Student Signature: ______________________");
        getContentPane().add(jLabel57);
        jLabel57.setBounds(30, 520, 337, 34);

        jLabel59.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel59.setText("Date & Time:");
        getContentPane().add(jLabel59);
        jLabel59.setBounds(20, 250, 100, 34);

        rfGWATF.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        rfGWATF.setEnabled(false);
        rfGWATF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfGWATFActionPerformed(evt);
            }
        });
        getContentPane().add(rfGWATF);
        rfGWATF.setBounds(90, 490, 141, 30);

        dateTimeTF.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        dateTimeTF.setEnabled(false);
        dateTimeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTimeTFActionPerformed(evt);
            }
        });
        getContentPane().add(dateTimeTF);
        dateTimeTF.setBounds(120, 253, 244, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gradeStudIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeStudIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeStudIDTFActionPerformed

    private void gradeStudIDTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeStudIDTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeStudIDTF1ActionPerformed

    private void rfStudIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfStudIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfStudIDTFActionPerformed

    private void rfStudNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfStudNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfStudNameTFActionPerformed

    private void rfCourseTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfCourseTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfCourseTFActionPerformed

    private void yearSectionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearSectionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearSectionTFActionPerformed

    private void acadYearTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acadYearTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acadYearTFActionPerformed

    private void semTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semTFActionPerformed

    private void rfGWATFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfGWATFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfGWATFActionPerformed

    private void dateTimeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTimeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTimeTFActionPerformed

    private void rfgradeTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_rfgradeTableAncestorAdded
        // TODO add your handling code here:
         rfgradeTable.getColumnModel().getColumn(0).setPreferredWidth(200);
    }//GEN-LAST:event_rfgradeTableAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acadYearTF;
    private javax.swing.JTextField dateTimeTF;
    private javax.swing.JTextField gradeStudIDTF;
    private javax.swing.JTextField gradeStudIDTF1;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField rfCourseTF;
    private javax.swing.JTextField rfGWATF;
    private javax.swing.JTextField rfStudIDTF;
    private javax.swing.JTextField rfStudNameTF;
    private javax.swing.JTable rfgradeTable;
    private javax.swing.JTextField semTF;
    private javax.swing.JTextField yearSectionTF;
    // End of variables declaration//GEN-END:variables

    boolean print() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
