/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author MARY ANGEL
 */
public class Dashboard extends javax.swing.JFrame {
    private String employeeId; 
    private PrintWriter out;
    private BufferedReader in;
    private Socket socket;


    /**
     * Creates new form Dashboard
     */
    public Dashboard(String empId, Socket socket, PrintWriter out, BufferedReader in) {
        initComponents();
        this.employeeId = empId;
        this.socket = socket;
        this.out = out;
        this.in = in;
        setTitle("Employee Dashboard - " + empId);
        loadEmployeeData();     
    }
      
    
    private void loadEmployeeData() {
        try {
            out.println("Dashboard|" + employeeId);
            out.flush();

            String response = in.readLine();
            if (response == null) {
                throw new IOException("Server disconnected");
            }

            if (response.startsWith("Dashboard|")) {
                String[] parts = response.split("\\|");
                if (parts.length >= 2) {
                    empName.setText(parts[1]);
                }
            } else if (response.startsWith("ERROR|")) {
                empName.setText("Data Unavailable");
                JOptionPane.showMessageDialog(this, 
                    response.substring(6), "Data Error", JOptionPane.ERROR_MESSAGE);
            } else {
                handleUnexpectedResponse(response);
            }
        } catch (IOException ex) {
            handleNetworkError("Failed to load employee data", ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dashboardTimeOutBTN = new javax.swing.JButton();
        dashboardTimeInBTN = new javax.swing.JButton();
        dashboardSubmitLeaveRequestBTN = new javax.swing.JButton();
        dashboardViewLeaveRequestBTN = new javax.swing.JButton();
        dashboardLogoutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.gray)));
        jPanel1.setMaximumSize(new java.awt.Dimension(899, 599));
        jPanel1.setMinimumSize(new java.awt.Dimension(899, 599));
        jPanel1.setPreferredSize(new java.awt.Dimension(899, 599));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 95, 155));
        jPanel2.setMaximumSize(new java.awt.Dimension(900, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(900, 80));
        jPanel2.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(830, 25, 32, 32);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whitelogo.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 10, 64, 64);

        empName.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        empName.setForeground(new java.awt.Color(255, 255, 255));
        empName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(empName);
        empName.setBounds(560, 25, 260, 30);

        jLabel3.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee Portal");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 30, 230, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 80);

        dashboardTimeOutBTN.setBackground(new java.awt.Color(0, 65, 106));
        dashboardTimeOutBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        dashboardTimeOutBTN.setForeground(new java.awt.Color(255, 255, 255));
        dashboardTimeOutBTN.setText("Time Out");
        dashboardTimeOutBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        dashboardTimeOutBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        dashboardTimeOutBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        dashboardTimeOutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardTimeOutBTNActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardTimeOutBTN);
        dashboardTimeOutBTN.setBounds(320, 200, 250, 40);

        dashboardTimeInBTN.setBackground(new java.awt.Color(0, 65, 106));
        dashboardTimeInBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        dashboardTimeInBTN.setForeground(new java.awt.Color(255, 255, 255));
        dashboardTimeInBTN.setText("Time In");
        dashboardTimeInBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        dashboardTimeInBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        dashboardTimeInBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        dashboardTimeInBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardTimeInBTNActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardTimeInBTN);
        dashboardTimeInBTN.setBounds(320, 140, 250, 40);

        dashboardSubmitLeaveRequestBTN.setBackground(new java.awt.Color(0, 65, 106));
        dashboardSubmitLeaveRequestBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        dashboardSubmitLeaveRequestBTN.setForeground(new java.awt.Color(255, 255, 255));
        dashboardSubmitLeaveRequestBTN.setText("Submit Leave Request");
        dashboardSubmitLeaveRequestBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        dashboardSubmitLeaveRequestBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        dashboardSubmitLeaveRequestBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        dashboardSubmitLeaveRequestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardSubmitLeaveRequestBTNActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardSubmitLeaveRequestBTN);
        dashboardSubmitLeaveRequestBTN.setBounds(320, 260, 250, 40);

        dashboardViewLeaveRequestBTN.setBackground(new java.awt.Color(0, 65, 106));
        dashboardViewLeaveRequestBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        dashboardViewLeaveRequestBTN.setForeground(new java.awt.Color(255, 255, 255));
        dashboardViewLeaveRequestBTN.setText("View My Leave Requests");
        dashboardViewLeaveRequestBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        dashboardViewLeaveRequestBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        dashboardViewLeaveRequestBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        dashboardViewLeaveRequestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardViewLeaveRequestBTNActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardViewLeaveRequestBTN);
        dashboardViewLeaveRequestBTN.setBounds(320, 320, 250, 40);

        dashboardLogoutBTN.setBackground(new java.awt.Color(0, 65, 106));
        dashboardLogoutBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        dashboardLogoutBTN.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLogoutBTN.setText("Logout");
        dashboardLogoutBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        dashboardLogoutBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        dashboardLogoutBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        dashboardLogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardLogoutBTNActionPerformed(evt);
            }
        });
        jPanel1.add(dashboardLogoutBTN);
        dashboardLogoutBTN.setBounds(320, 380, 250, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 899, 599);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardTimeInBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardTimeInBTNActionPerformed
        try {
            out.println("TIME_IN|" + employeeId);
            out.flush();
            
            String response = in.readLine();
            if (response == null) {
                throw new IOException("No server response");
            }
            
            if (response.startsWith("SUCCESS|")) {
                JOptionPane.showMessageDialog(this, response.substring(8));
            } else if (response.startsWith("ERROR|")) {
                JOptionPane.showMessageDialog(this, 
                    response.substring(6), "Time In Error", JOptionPane.ERROR_MESSAGE);
            } else {
                handleUnexpectedResponse(response);
            }
        } catch (IOException ex) {
            handleNetworkError("Failed to record time in", ex);
        }
    }//GEN-LAST:event_dashboardTimeInBTNActionPerformed

    private void dashboardTimeOutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardTimeOutBTNActionPerformed
        try {
            out.println("TIME_OUT|" + employeeId);
            out.flush();
            
            String response = in.readLine();
            if (response == null) {
                throw new IOException("No server response");
            }
            
            if (response.startsWith("SUCCESS|")) {
                JOptionPane.showMessageDialog(this, response.substring(8));
            } else if (response.startsWith("ERROR|")) {
                JOptionPane.showMessageDialog(this, 
                    response.substring(6), "Time In Error", JOptionPane.ERROR_MESSAGE);
            } else {
                handleUnexpectedResponse(response);
            }
        } catch (IOException ex) {
            handleNetworkError("Failed to record time in", ex);
        }
    }//GEN-LAST:event_dashboardTimeOutBTNActionPerformed

    private void dashboardSubmitLeaveRequestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardSubmitLeaveRequestBTNActionPerformed
        // TODO add your handling code here:
        LeaveRequestForm leaveRequestForm = new LeaveRequestForm(employeeId, socket, out, in);
        leaveRequestForm.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_dashboardSubmitLeaveRequestBTNActionPerformed

    private void dashboardViewLeaveRequestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardViewLeaveRequestBTNActionPerformed
        // TODO add your handling code here:
        MyLeaveRequest leaveRequest = new MyLeaveRequest(employeeId, socket, out, in);
        leaveRequest.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardViewLeaveRequestBTNActionPerformed

    private void dashboardLogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardLogoutBTNActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to log out?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
        );
    
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                out.println("LOGOUT|" + employeeId);
                out.flush();

                String response = in.readLine();
                if (response != null && !response.startsWith("LOGOUT_SUCCESS")) {
                    JOptionPane.showMessageDialog(this, 
                        "Server error during logout: " + response,
                        "Logout Error", 
                        JOptionPane.WARNING_MESSAGE);
                }

                closeConnections();

                this.dispose();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, 
                    "Error during logout: " + ex.getMessage(),
                    "Logout Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_dashboardLogoutBTNActionPerformed
    
    private void handleUnexpectedResponse(String response) {
        JOptionPane.showMessageDialog(this,
            "Unexpected server response: " + response,
            "Protocol Error", JOptionPane.ERROR_MESSAGE);
        closeConnections();
    }

    private void handleNetworkError(String action, IOException ex) {
        JOptionPane.showMessageDialog(this,
            action + ": " + ex.getMessage(),
            "Network Error", JOptionPane.ERROR_MESSAGE);
        closeConnections();
        dispose();
    }

    private void closeConnections() {
        try {
            if (out != null) out.close();
            if (in != null) in.close();
            if (socket != null && !socket.isClosed()) socket.close();
        } catch (IOException e) {
            System.err.println("Error closing connections: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardLogoutBTN;
    private javax.swing.JButton dashboardSubmitLeaveRequestBTN;
    private javax.swing.JButton dashboardTimeInBTN;
    private javax.swing.JButton dashboardTimeOutBTN;
    private javax.swing.JButton dashboardViewLeaveRequestBTN;
    private javax.swing.JLabel empName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
