/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Date;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author MARY ANGEL
 */
public class LeaveRequestForm extends javax.swing.JFrame {
    private String employeeId; 
    private PrintWriter out;
    private BufferedReader in;
    private Socket socket;

    /**
     * Creates new form LeaveRequestForm
     */
    public LeaveRequestForm(String empId, Socket socket, PrintWriter out, BufferedReader in) {
        initComponents();
        this.employeeId = empId;
        this.socket = socket;
        this.out = out;
        this.in = in;
        setTitle("Leave Request - " + empId);
        setCurrentDate();
        startClock();      
    }
    private void setCurrentDate() {
    LocalDate today = LocalDate.now();
    DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    JLabelDate.setText(today.format(dateFormat));
}
    private void startClock() {
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                LocalTime now = LocalTime.now();
                DateTimeFormatter timeFormat = DateTimeFormatter.ofPattern("HH:mm:ss"); 
                JLabelTime.setText(now.format(timeFormat));
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JLabelTime = new javax.swing.JLabel();
        JLabelDate = new javax.swing.JLabel();
        ReturnDashboardBTN = new javax.swing.JButton();
        leaveRequestSubmitBTN = new javax.swing.JButton();
        leaveRequestClearFormtBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JComboleaveType = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        leaveEndDateJDateChooser = new com.toedter.calendar.JDateChooser();
        leaveStartDateJDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReason = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 95, 155));
        jPanel4.setMaximumSize(new java.awt.Dimension(900, 80));
        jPanel4.setMinimumSize(new java.awt.Dimension(900, 80));
        jPanel4.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whitelogo.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 10, 64, 64);

        jLabel11.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Leave Request Portal");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(90, 30, 230, 20);

        JLabelTime.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        JLabelTime.setForeground(new java.awt.Color(255, 255, 255));
        JLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel4.add(JLabelTime);
        JLabelTime.setBounds(610, 40, 250, 20);

        JLabelDate.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        JLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        JLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel4.add(JLabelDate);
        JLabelDate.setBounds(710, 20, 150, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 900, 80);

        ReturnDashboardBTN.setBackground(new java.awt.Color(0, 65, 106));
        ReturnDashboardBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        ReturnDashboardBTN.setForeground(new java.awt.Color(255, 255, 255));
        ReturnDashboardBTN.setText("Back to Dashboard");
        ReturnDashboardBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        ReturnDashboardBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        ReturnDashboardBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        ReturnDashboardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnDashboardBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ReturnDashboardBTN);
        ReturnDashboardBTN.setBounds(610, 490, 200, 40);

        leaveRequestSubmitBTN.setBackground(new java.awt.Color(56, 142, 60));
        leaveRequestSubmitBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        leaveRequestSubmitBTN.setForeground(new java.awt.Color(255, 255, 255));
        leaveRequestSubmitBTN.setText("Submit");
        leaveRequestSubmitBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        leaveRequestSubmitBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        leaveRequestSubmitBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        leaveRequestSubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveRequestSubmitBTNActionPerformed(evt);
            }
        });
        jPanel1.add(leaveRequestSubmitBTN);
        leaveRequestSubmitBTN.setBounds(100, 490, 200, 40);

        leaveRequestClearFormtBTN.setBackground(new java.awt.Color(0, 65, 106));
        leaveRequestClearFormtBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        leaveRequestClearFormtBTN.setForeground(new java.awt.Color(255, 255, 255));
        leaveRequestClearFormtBTN.setText("Clear Form");
        leaveRequestClearFormtBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        leaveRequestClearFormtBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        leaveRequestClearFormtBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        leaveRequestClearFormtBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveRequestClearFormtBTNActionPerformed(evt);
            }
        });
        jPanel1.add(leaveRequestClearFormtBTN);
        leaveRequestClearFormtBTN.setBounds(360, 490, 200, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray), null));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 45, 75));
        jLabel10.setText("Reason:");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(380, 100, 90, 20);

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 45, 75));
        jLabel1.setText("M&J SYSTEMS CO.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(320, 10, 230, 35);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(250, 0, 64, 64);

        jLabel12.setFont(new java.awt.Font("Dubai Light", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 45, 75));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Leave Request Form");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(260, 40, 230, 20);

        JComboleaveType.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        JComboleaveType.setForeground(new java.awt.Color(0, 45, 75));
        JComboleaveType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacation Leave", "Sick Leave", "Emergency Leave" }));
        jPanel2.add(JComboleaveType);
        JComboleaveType.setBounds(130, 110, 180, 21);

        jLabel13.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 45, 75));
        jLabel13.setText("Leave Type:");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(40, 110, 90, 20);

        jLabel14.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 45, 75));
        jLabel14.setText("Start Date:");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 150, 90, 20);

        jLabel15.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 45, 75));
        jLabel15.setText("End Date:");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(40, 190, 90, 20);
        jPanel2.add(leaveEndDateJDateChooser);
        leaveEndDateJDateChooser.setBounds(130, 190, 180, 22);
        jPanel2.add(leaveStartDateJDateChooser);
        leaveStartDateJDateChooser.setBounds(130, 150, 180, 22);

        jTextAreaReason.setColumns(20);
        jTextAreaReason.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReason);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(380, 120, 310, 100);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(100, 100, 710, 370);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void leaveRequestClearFormtBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveRequestClearFormtBTNActionPerformed
        // TODO add your handling code here:
        JComboleaveType.setSelectedIndex(0); 
        leaveStartDateJDateChooser.setDate(null); 
        leaveEndDateJDateChooser.setDate(null);  
        jTextAreaReason.setText(""); 
    }//GEN-LAST:event_leaveRequestClearFormtBTNActionPerformed

    private void leaveRequestSubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveRequestSubmitBTNActionPerformed
        // TODO add your handling code here:
        String leaveType = JComboleaveType.getSelectedItem().toString();
        Date startDate = leaveStartDateJDateChooser.getDate();
        Date endDate = leaveEndDateJDateChooser.getDate();
        String reason = jTextAreaReason.getText();
        
        if (startDate == null || endDate == null) {
            JOptionPane.showMessageDialog(this, "Please select both start and end dates");
            return;
        }
        if (reason.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a reason for leave");
            return;
        }
        if (startDate.after(endDate)) {
            JOptionPane.showMessageDialog(this, "End date cannot be before start date");
            return;
        }

        try {
            out.println("SUBMIT_LEAVE_REQUEST|" + employeeId + "|" + leaveType + "|" +
                       new java.sql.Date(startDate.getTime()) + "|" +
                       new java.sql.Date(endDate.getTime()) + "|" + reason);
            out.flush();

            String response = in.readLine();
            if (response == null) {
                throw new IOException("No response from server");
            }

            if (response.startsWith("SUCCESS|")) {
                JOptionPane.showMessageDialog(this, 
                    "Leave request submitted successfully!",
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else if (response.startsWith("ERROR|")) {
                JOptionPane.showMessageDialog(this, 
                    response.substring(6),
                    "Submission Error", 
                    JOptionPane.ERROR_MESSAGE);
            } else {
                handleUnexpectedResponse(response);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                "Network error: " + ex.getMessage(),
                "Connection Error",
                JOptionPane.ERROR_MESSAGE);
            closeConnections();
        }
    }//GEN-LAST:event_leaveRequestSubmitBTNActionPerformed

    private void ReturnDashboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnDashboardBTNActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard = new Dashboard(employeeId, socket, out, in);
        dashboard.setVisible(true);
        
        this.dispose(); 
    }//GEN-LAST:event_ReturnDashboardBTNActionPerformed
  
    private void handleUnexpectedResponse(String response) {
        JOptionPane.showMessageDialog(this,
            "Unexpected server response: " + response,
            "Protocol Error",
            JOptionPane.ERROR_MESSAGE);
        closeConnections();
    }

    private void closeConnections() {
        try {
            if (out != null) out.close();
            if (in != null) in.close();
            if (socket != null && !socket.isClosed()) socket.close();
        } catch (IOException e) {
            System.err.println("Error closing connections: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboleaveType;
    private javax.swing.JLabel JLabelDate;
    private javax.swing.JLabel JLabelTime;
    private javax.swing.JButton ReturnDashboardBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaReason;
    private com.toedter.calendar.JDateChooser leaveEndDateJDateChooser;
    private javax.swing.JButton leaveRequestClearFormtBTN;
    private javax.swing.JButton leaveRequestSubmitBTN;
    private com.toedter.calendar.JDateChooser leaveStartDateJDateChooser;
    // End of variables declaration//GEN-END:variables
}
