/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARY ANGEL
 */
public class MyLeaveRequest extends javax.swing.JFrame {
    private String employeeId; 
    private PrintWriter out;
    private BufferedReader in;
    private Socket socket;
    

    /**
     * Creates new form MyLeaveRequest
     */
    public MyLeaveRequest(String empId, Socket socket, PrintWriter out, BufferedReader in) {
        this.employeeId = empId;
        this.socket = socket;
        this.out = out;
        this.in = in;

        initComponents();
        setCurrentDate();
        startClock();
    }
  private void setCurrentDate() {
    LocalDate today = LocalDate.now();
    DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    JLabelDate.setText(today.format(dateFormat));
    }
    private void startClock() {
    Timer timer = new Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            LocalTime now = LocalTime.now();
            DateTimeFormatter timeFormat = DateTimeFormatter.ofPattern("HH:mm:ss"); 
            JLabelTime.setText(now.format(timeFormat));
        }
    });
    timer.start();
    }
    
    private void loadLeaveRequests() {
        DefaultTableModel model = (DefaultTableModel) myLeaveRequestTBL.getModel();
        model.setRowCount(0); 

        try {
            out.println("GET_LEAVE_REQUESTS|" + employeeId);
            out.flush();

            String response;
            while (!(response = in.readLine()).equals("END_OF_DATA")) {
                if (response.startsWith("LEAVE_DATA|")) {
                    String[] data = response.split("\\|");
                    if (data.length >= 6) {
                        model.addRow(new Object[]{
                            data[1],
                            data[2],
                            data[3],
                            data[4], 
                            data[5]  
                        });
                    }
                } else if (response.startsWith("ERROR|")) {
                    JOptionPane.showMessageDialog(this, 
                        response.substring(6), 
                        "Data Error", 
                        JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                "Network error: " + ex.getMessage(),
                "Connection Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JLabelDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JLabelTime = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myLeaveRequestTBL = new javax.swing.JTable();
        returnDashboardBTN = new javax.swing.JButton();
        refreshBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 95, 155));
        jPanel4.setMaximumSize(new java.awt.Dimension(900, 80));
        jPanel4.setMinimumSize(new java.awt.Dimension(900, 80));
        jPanel4.setLayout(null);

        JLabelDate.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        JLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        JLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel4.add(JLabelDate);
        JLabelDate.setBounds(710, 20, 150, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whitelogo.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 10, 64, 64);

        JLabelTime.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        JLabelTime.setForeground(new java.awt.Color(255, 255, 255));
        JLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel4.add(JLabelTime);
        JLabelTime.setBounds(610, 40, 250, 20);

        jLabel12.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("My Leave Request Portal");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(90, 30, 230, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 900, 80);

        myLeaveRequestTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Leave Type", "Start Date", "End Date", "Status", "Reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(myLeaveRequestTBL);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 160, 710, 320);

        returnDashboardBTN.setBackground(new java.awt.Color(0, 65, 106));
        returnDashboardBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        returnDashboardBTN.setForeground(new java.awt.Color(255, 255, 255));
        returnDashboardBTN.setText("Back to Dashboard");
        returnDashboardBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        returnDashboardBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        returnDashboardBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        returnDashboardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDashboardBTNActionPerformed(evt);
            }
        });
        jPanel1.add(returnDashboardBTN);
        returnDashboardBTN.setBounds(350, 500, 200, 40);

        refreshBTN.setBackground(new java.awt.Color(56, 142, 60));
        refreshBTN.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        refreshBTN.setForeground(new java.awt.Color(255, 255, 255));
        refreshBTN.setText("Refresh");
        refreshBTN.setMaximumSize(new java.awt.Dimension(250, 40));
        refreshBTN.setMinimumSize(new java.awt.Dimension(250, 40));
        refreshBTN.setPreferredSize(new java.awt.Dimension(250, 40));
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });
        jPanel1.add(refreshBTN);
        refreshBTN.setBounds(650, 120, 160, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnDashboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDashboardBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();

        Dashboard dashboard = new Dashboard(employeeId, socket, out, in);
        dashboard.setVisible(true);
    }//GEN-LAST:event_returnDashboardBTNActionPerformed

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        // TODO add your handling code here:
        loadLeaveRequests();
    }//GEN-LAST:event_refreshBTNActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelDate;
    private javax.swing.JLabel JLabelTime;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable myLeaveRequestTBL;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JButton returnDashboardBTN;
    // End of variables declaration//GEN-END:variables
}
