/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author MARY ANGEL
 */
public class UserLogin extends javax.swing.JFrame {
    private boolean passwordVisible = false;
    private PrintWriter out;
    private BufferedReader in;
    private Socket socket;


    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
    }
  
    
    private boolean connectToServer() {
        try {
            socket = new Socket("192.168.1.4", 1234); // isli ang host ka ip address mo
            out = new PrintWriter(socket.getOutputStream(), true);
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            System.out.println("Connected to server.");
            return true;
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Failed to connect to the server: " + e.getMessage(),
                    "Connection Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void closeConnections() {
        try {
            if (out != null) {
                out.close();
            }
            if (in != null) {
                in.close();
            }
            if (socket != null && !socket.isClosed()) {
                socket.close();
            }
        } catch (IOException e) {
            System.err.println("Error closing connections: " + e.getMessage());
        } finally {
            out = null;
            in = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        userLoginBTN = new javax.swing.JButton();
        empIdTF = new javax.swing.JTextField();
        empPassPF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empSeePassBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 350));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray), null));
        jPanel2.setMaximumSize(new java.awt.Dimension(420, 350));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 350));
        jPanel2.setLayout(null);

        userLoginBTN.setBackground(new java.awt.Color(0, 65, 106));
        userLoginBTN.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        userLoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        userLoginBTN.setText("Login");
        userLoginBTN.setMaximumSize(new java.awt.Dimension(230, 35));
        userLoginBTN.setMinimumSize(new java.awt.Dimension(230, 35));
        userLoginBTN.setPreferredSize(new java.awt.Dimension(230, 35));
        userLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginBTNActionPerformed(evt);
            }
        });
        jPanel2.add(userLoginBTN);
        userLoginBTN.setBounds(100, 210, 230, 35);

        empIdTF.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        empIdTF.setMaximumSize(new java.awt.Dimension(230, 35));
        empIdTF.setMinimumSize(new java.awt.Dimension(230, 35));
        empIdTF.setPreferredSize(new java.awt.Dimension(230, 35));
        jPanel2.add(empIdTF);
        empIdTF.setBounds(160, 80, 230, 35);

        empPassPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        empPassPF.setMaximumSize(new java.awt.Dimension(230, 35));
        empPassPF.setMinimumSize(new java.awt.Dimension(230, 35));
        empPassPF.setPreferredSize(new java.awt.Dimension(230, 35));
        empPassPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPassPFActionPerformed(evt);
            }
        });
        jPanel2.add(empPassPF);
        empPassPF.setBounds(160, 130, 200, 35);

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 45, 75));
        jLabel1.setText("M&J SYSTEMS CO.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 20, 230, 35);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel2.setText("Employee ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 90, 110, 16);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 140, 90, 16);

        empSeePassBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        empSeePassBTN.setMaximumSize(new java.awt.Dimension(30, 35));
        empSeePassBTN.setMinimumSize(new java.awt.Dimension(30, 35));
        empSeePassBTN.setPreferredSize(new java.awt.Dimension(30, 35));
        empSeePassBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSeePassBTNActionPerformed(evt);
            }
        });
        jPanel2.add(empSeePassBTN);
        empSeePassBTN.setBounds(360, 130, 30, 35);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 10, 64, 64);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void empPassPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPassPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPassPFActionPerformed

    private void userLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginBTNActionPerformed
        // TODO add your handling code here:
        String empIdStr = empIdTF.getText().trim();
        String password = new String(empPassPF.getPassword()).trim();

        if (empIdStr.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter both Employee ID and Password.");
            return;
        }

        userLoginBTN.setEnabled(false);  

        if (!connectToServer()) {
            userLoginBTN.setEnabled(true);
            return;
        }

        try {
            String initialResponse = in.readLine();
            if (initialResponse == null || !initialResponse.equals("CONNECTED")) {
                JOptionPane.showMessageDialog(null, "Unexpected initial response: " + initialResponse);
                closeConnections();
                userLoginBTN.setEnabled(true);
                return;
            }

            out.println("LOGIN|" + empIdStr + "|" + password);

            String loginResponse = in.readLine();

            if (loginResponse == null) {
                JOptionPane.showMessageDialog(null, "No response from server. Connection lost.");
                closeConnections();
                userLoginBTN.setEnabled(true);
                return;
            }

            if ("LOGIN_SUCCESS".equals(loginResponse)) {
                JOptionPane.showMessageDialog(null, "Login successful!");
                // Success - keep connection open and proceed to dashboard
                Dashboard dashboard = new Dashboard(empIdStr, socket, out, in);
                dashboard.setVisible(true);
                this.dispose();
            } 
            else if (loginResponse.startsWith("LOGIN_FAILED")) {
                JOptionPane.showMessageDialog(null, "Login failed: " + 
                    (loginResponse.contains("|") ? loginResponse.split("\\|")[1] : "Invalid credentials"));
                closeConnections();
                userLoginBTN.setEnabled(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "Unexpected login response: " + loginResponse);
                closeConnections();
                userLoginBTN.setEnabled(true);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Connection error: " + e.getMessage());
            closeConnections();
            userLoginBTN.setEnabled(true);
        }
    }//GEN-LAST:event_userLoginBTNActionPerformed

    private void empSeePassBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSeePassBTNActionPerformed
        // TODO add your handling code here:
        if (passwordVisible) {
            empPassPF.setEchoChar('•'); 
            passwordVisible = false;
        } else {
            empPassPF.setEchoChar((char) 0); 
            passwordVisible = true;
        }        
    }//GEN-LAST:event_empSeePassBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empIdTF;
    private javax.swing.JPasswordField empPassPF;
    private javax.swing.JButton empSeePassBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton userLoginBTN;
    // End of variables declaration//GEN-END:variables
}
