/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.raven.event.EventTimePicker;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;


/**
 *
 * @author user
 */
public class ICT108 extends javax.swing.JFrame {
 

    /**
     * Creates new form ICT108
     */
    public ICT108() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
         timePicker1.addEventTimePicker(new EventTimePicker() {
        @Override
        public void timeSelected(String time) {
            txt.setText(time); // Set the selected time to txt text field
        }
    });
    
         timePicker2.addEventTimePicker(new EventTimePicker() {
        @Override
        public void timeSelected(String time) {
            tst.setText(time); // Set the selected time to tst text field
        }
    });
         
         timePicker1.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            System.out.println("Class Start: " + timePicker1.getSelectedTime()); // Set the selected time to txt text field
        }
    });
         
          timePicker2.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            System.out.println("Class End: " + timePicker2.getSelectedTime()); // Set the selected time to txt text field
        }
    });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        timePicker1 = new com.raven.swing.TimePicker();
        timePicker2 = new com.raven.swing.TimePicker();
        txt = new javax.swing.JTextField();
        tst = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(jDayChooser1);
        jDayChooser1.setBounds(320, 40, 350, 260);

        timePicker1.setDisplayText(txt);
        getContentPane().add(timePicker1);
        timePicker1.setBounds(110, 310, 238, 332);
        getContentPane().add(timePicker2);
        timePicker2.setBounds(440, 310, 238, 332);
        getContentPane().add(txt);
        txt.setBounds(750, 400, 200, 30);
        getContentPane().add(tst);
        tst.setBounds(750, 540, 200, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("End");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(750, 510, 80, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Start");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(750, 370, 80, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
       
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.raven.swing.TimePicker timePicker1;
    private com.raven.swing.TimePicker timePicker2;
    private javax.swing.JTextField tst;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}