/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

  /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seePW = new javax.swing.JButton();
        pinTF = new javax.swing.JPasswordField();
        loginBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        accNOTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registerBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        seePW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seePW.setForeground(new java.awt.Color(255, 255, 255));
        seePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePWActionPerformed(evt);
            }
        });
        getContentPane().add(seePW);
        seePW.setBounds(1130, 430, 60, 70);

        pinTF.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        pinTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTFActionPerformed(evt);
            }
        });
        getContentPane().add(pinTF);
        pinTF.setBounds(800, 430, 330, 70);

        loginBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        loginBTN.setText("Login");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        getContentPane().add(loginBTN);
        loginBTN.setBounds(890, 530, 140, 40);

        exitBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(exitBTN);
        exitBTN.setBounds(1040, 530, 140, 40);

        accNOTF.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        accNOTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(accNOTF);
        accNOTF.setBounds(800, 350, 390, 60);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel2.setText("PIN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 440, 170, 50);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 350, 170, 50);

        registerBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        registerBTN.setText("Register");
        registerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTNActionPerformed(evt);
            }
        });
        getContentPane().add(registerBTN);
        registerBTN.setBounds(940, 590, 220, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
     String username = accNOTF.getText();
    String pin = new String(pinTF.getPassword());
    if (isAccountValid(username, pin)) {
        JOptionPane.showMessageDialog(this, "Login successful!");
        // Hide the Login frame
        this.setVisible(false);
        // Create an instance of the Rooms class and make it visible
        Rooms rooms = new Rooms();
        rooms.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Invalid username or PIN. Please try again.");
    }
}   

private boolean isAccountValid(String username, String pin) {
    String[] usernameAndPIN = readUsernameAndPIN(username, pin);
    if (usernameAndPIN != null && usernameAndPIN[1].equals(pin)) {
        return true;
    }
    return false;
    }//GEN-LAST:event_loginBTNActionPerformed

    public static String[] readUsernameAndPIN(String username, String pin) {
    String filePath = "C:\\Users\\admin\\Desktop\\SSLS\\ScheduledSmartLockSystem\\src\\accounts.txt";
    String line;
    String[] usernameAndPIN = null;
    boolean foundUsername = false;
    
    try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
        while ((line = reader.readLine()) != null) {
            if (line.contains("Username") && line.contains(username)) {
                foundUsername = true;
            }
            if (foundUsername && line.contains("PIN")) {
                String[] parts = line.split(":");
                if (parts.length == 2) {
                    usernameAndPIN = new String[]{username, parts[1].trim()};
                    break;
                }
            }
        }
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
    
    return usernameAndPIN;
}
  
    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
       JFrame frame = new JFrame("EXIT");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want Exit", "EXIT", 
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
        
       
                
    }//GEN-LAST:event_exitBTNActionPerformed

    private boolean passwordVisible = false;
    private void pinTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinTFActionPerformed

    private void seePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePWActionPerformed
        // TODO add your handling code here:
        passwordVisible = !passwordVisible;

        if (passwordVisible) {
            pinTF.setEchoChar((char) 0);
        } else {
            pinTF.setEchoChar('*'); 
        }
    }//GEN-LAST:event_seePWActionPerformed

    private void registerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBTNActionPerformed
        // TODO add your handling code here:
        Register register = new Register();
        register.setVisible(true);
        
    }//GEN-LAST:event_registerBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
       
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNOTF;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBTN;
    private javax.swing.JPasswordField pinTF;
    private javax.swing.JButton registerBTN;
    private javax.swing.JButton seePW;
    // End of variables declaration//GEN-END:variables
}