/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class Register extends javax.swing.JFrame {

  /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
    }
    private void saveAccounts(){
        String name = nameTF.getText();
        String username = usernameTF.getText();
        String pin = pinTF.getText();
        
        String allInfo =
        "\nName: " + name +
        "\nUsername: " +username +
        "\nPIN: " + pin;
    
    String filePath = "C:\\Users\\admin\\Desktop\\SSLS\\ScheduledSmartLockSystem\\src\\accounts.txt";

        try (PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(filePath, true)))) {
        writer.println(allInfo);
        writer.println();
    } catch (IOException e) {
        e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seePW = new javax.swing.JButton();
        pinTF = new javax.swing.JPasswordField();
        exitBTN = new javax.swing.JButton();
        usernameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        registerBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        seePW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seePW.setForeground(new java.awt.Color(255, 255, 255));
        seePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePWActionPerformed(evt);
            }
        });
        getContentPane().add(seePW);
        seePW.setBounds(1130, 380, 60, 70);

        pinTF.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        pinTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTFActionPerformed(evt);
            }
        });
        getContentPane().add(pinTF);
        pinTF.setBounds(800, 380, 330, 70);

        exitBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(exitBTN);
        exitBTN.setBounds(1050, 480, 140, 40);

        usernameTF.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        usernameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(usernameTF);
        usernameTF.setBounds(800, 300, 390, 60);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 240, 170, 50);

        registerBTN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        registerBTN.setText("Register");
        registerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTNActionPerformed(evt);
            }
        });
        getContentPane().add(registerBTN);
        registerBTN.setBounds(820, 480, 220, 40);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(630, 300, 170, 50);

        nameTF.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        nameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(nameTF);
        nameTF.setBounds(800, 220, 390, 60);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel5.setText("PIN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 390, 170, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
       JFrame frame = new JFrame("EXIT");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want Exit", "EXIT", 
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
        
       
                
    }//GEN-LAST:event_exitBTNActionPerformed

    private boolean passwordVisible = false;
    private void pinTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinTFActionPerformed

    private void seePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePWActionPerformed
        // TODO add your handling code here:
        passwordVisible = !passwordVisible;

        if (passwordVisible) {
            pinTF.setEchoChar((char) 0);
        } else {
            pinTF.setEchoChar('*'); 
        }
    }//GEN-LAST:event_seePWActionPerformed

    private void registerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBTNActionPerformed
        // TODO add your handling code here:
        saveAccounts();
        JOptionPane.showMessageDialog(this, "Registration successful!");
        nameTF.setText("");
        usernameTF.setText("");
        pinTF.setText("");
    }//GEN-LAST:event_registerBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField pinTF;
    private javax.swing.JButton registerBTN;
    private javax.swing.JButton seePW;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}