/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JFrame;


/**
 *
 * @author user
 */
public class Rooms extends javax.swing.JFrame {

  /** 
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton4.setText("ICT- 104");
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 0, 342, 384);

        jButton5.setText("ICT-105");
        getContentPane().add(jButton5);
        jButton5.setBounds(340, 0, 342, 384);

        jButton6.setText("ICT-106");
        getContentPane().add(jButton6);
        jButton6.setBounds(680, 0, 342, 384);

        jButton7.setText("ICT-107");
        getContentPane().add(jButton7);
        jButton7.setBounds(1020, 0, 342, 384);

        jButton8.setText("ICT-108");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(0, 380, 342, 384);

        jButton9.setText("ICT-201");
        getContentPane().add(jButton9);
        jButton9.setBounds(340, 380, 342, 384);

        jButton10.setText("ICT-202");
        getContentPane().add(jButton10);
        jButton10.setBounds(680, 380, 342, 384);

        jButton11.setText("ICT-203");
        getContentPane().add(jButton11);
        jButton11.setBounds(1020, 380, 342, 384);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ICT108 ict108 = new ICT108();
        ict108.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}